version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - UVICORN_PORT=8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Expose the React app on port 3000
    networks:
      - app-network
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge
