name: Build and Push Docker Image

# Trigger the workflow on pushes to specific branches
on:
  push:
    branches:
      - main  # Change to your default branch if needed
  pull_request:
    branches:
      - main  # Optional: Runs for pull requests targeting 'main'

jobs:
  docker:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the workflow

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:${{ github.sha }}

      # Step 4: Verify that the image was pushed successfully (optional)
      - name: Verify Docker Image Push
        run: |
          echo "Verifying that the Docker image was pushed to Docker Hub..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
